#
###################################
# Site wide configuration
####################################
#
title: Blog | K C Sreevasthavan 
email:
description: This blog is maintained by K C Sreevasthavan. You can find interesing 
  tutorials, free resources(themes, tips, designs), articles, music etc here.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/India
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: K C Sreevasthavan
  avatar: avatar.jpg
  job: Software engineer, traveller, entreprenuer, freelancer, photographer
  bio: "Graduated from National Institute of Technology Calicut, Kerala. <br>Loves travelling, photography, programming, FOSS, web development, <br>music, art, anything new and creative"
  email: sreevasthavan@gmail.com
  disqus-shortname: vasthav-github-io 
  twitter: me_vasthav
  facebook: sree.vasthavan
  google:
    plus: #username
    analytics: UA-84213835-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: vasthav
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sreevasthavan
  xing: #username
  instagram: vasthav
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: david_vasthav
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username

#########################
# minify HTML
#########################
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

sass:
  style: compressed
